scalar Date

type Resume {
    email: String
    url: String
    github: String
    location: String
    name: String
    objective: String
    languages: [String]
    experience: [Linear]
    education: [Linear]
    affiliations: [Linear]
}

type Linear {
    title: String
    subTitle: String
    location: String
    startDate: Date
    endDate: Date
    points: [String]
}
