#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Ensure we're in the project root
cd "$(dirname "$0")/.."

# Ensure node is available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Run checks and build
npx astro check && npx astro build && node ./utils/pdf-convert.js

# Stage the newly generated PDF file
git add public/docs/resume.pdf

git commit --amend --no-edit --no-verify
