name: CI

on:
    pull_request:
      branches-ignore: 
        - 'release/*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref_name, 'release/')"

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        echo "Running tests..."
        # Your test commands go here
