name: Release

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

    
      - name: Check for single commit and tag
        id: check
        run: |
          # Fetch all tags from the remote
          git fetch --tags
      
          # Get the list of all commits in the PR
          COMMIT_LIST=$(git rev-list HEAD ^${{ github.event.pull_request.base.sha }})
      
          # Variable to track if a tag was found
          TAG_FOUND="false"
      
          # Loop through each commit to check for a tag
          for COMMIT in $COMMIT_LIST; do
            TAG=$(git tag --contains $COMMIT)
            if [ ! -z "$TAG" ]; then
              TAG_FOUND="true"
              break
            fi
          done
      
          if [ "$TAG_FOUND" == "false" ]; then
            echo "None of the commits are tagged"
            echo "::set-output name=proceed::false"
          else
            echo "::set-output name=proceed::true"
          fi

      - name: Set node
        if: steps.check.outputs.proceed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Run changelogithub
        if: steps.check.outputs.proceed == 'true'
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    


  # release
