name: Release

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'release/*'
  pull_request_target:
    types: [ closed ]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

    
      - name: Check for single commit and tag
        id: check
        run: |
          # Fetch all tags from the remote
          git fetch --tags

          # Get the commit SHA for the latest commit in the PR
          LATEST_COMMIT_SHA=$(git rev-parse HEAD)

          # Get the number of commits in the PR
          COMMIT_COUNT=$(git rev-list --count HEAD ^${{ github.event.pull_request.base.sha }})

          # Get the tag associated with the latest commit
          TAG=$(git tag --contains $LATEST_COMMIT_SHA)

          if [ "$COMMIT_COUNT" -ne "1" ]; then
            echo "PR must contain exactly one commit"
            echo "::set-output name=proceed::false"
          elif [ -z "$TAG" ]; then
            echo "The commit must be tagged"
            echo "::set-output name=proceed::false"
          else
            echo "::set-output name=proceed::true"
          fi

      - name: Set node
        if: steps.check.outputs.proceed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Run changelogithub
        if: steps.check.outputs.proceed == 'true'
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    


  # release
